# Generated by Django 5.1.6 on 2025-03-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Women_ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.CharField(max_length=255)),
                ('EVENT', models.TextField()),
                ('VENUE', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Youth_ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.CharField(max_length=255)),
                ('EVENT', models.TextField()),
                ('VENUE', models.CharField(max_length=255)),
            ],
        ),
    ]
