# Generated by Django 5.1.6 on 2025-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women_ministry',
            name='DATE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='youth_ministry',
            name='DATE',
            field=models.DateField(),
        ),
    ]
