# Generated by Django 5.1.6 on 2025-03-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0002_alter_women_ministry_date_alter_youth_ministry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Men_ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('EVENT', models.TextField()),
                ('VENUE', models.CharField(max_length=255)),
            ],
        ),
    ]
